sudo: false

language: node_js
node_js:
  - 6.1

cache: yarn

before_install:
  - npm install codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run build
  - ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN

branches:
  only:
    - master
