sudo: false

language: node_js
node_js:
  - 6.1

cache:
  directories:
    - node_modules

before_install:
  - npm install codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: script
  script: git checkout . && npm run build && ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN
  on:
    branch: master

branches:
  only:
    - master
